os:
  - linux
python:
  - "2.7"
  - "3.6"
  - "nightly" # currently points to 3.7-dev

dist: trusty
sudo: required
language: python

addons:
  apt:
    packages:
      - git
      - libopenblas-base


# compiler:
#   - gcc
#   - clang

# cache:
#   directories:
#   - $HOME/OpenBlasInstall

before_install:
  # Show build setup
  # - ls $HOME/OpenBlasInstall/lib || (cd /tmp/ && git clone https://github.com/xianyi/OpenBLAS.git -b master && cd OpenBLAS && (make NO_AFFINITY=1 -j$(getconf _NPROCESSORS_ONLN) 2>/dev/null >/dev/null) && make PREFIX=$HOME/OpenBlasInstall install)
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - python --version
  - git --version
  - pip install -r requirements.txt

install:
  # git describe requires complete history
  # - travis_retry git fetch --unshallow
  - python setup.py install

script: 
  - python helpTest.py | grep PyDSM
  # - pytest
  
after_success:
  - echo "OK, all done."

notifications:
  email:
    recipients:
      - ralic.lo.eng@ieee.org
    on_success: always # default: change
    on_failure: never # default: always

